<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0TCCTUB" ignored="0" name="Test" tests="3" failures="1" timestamp="2021-03-23T11:20:58 IST" time="38.958" errors="0">
  <testcase name="statement_Collection_Create" time="11.028" classname="Transactions.StatementCollection"/>
  <testcase name="FieldValidation" time="10.546" classname="Transactions.StatementCollection">
    <failure type="java.lang.AssertionError" message="Test failed : Record Saved Successfull. :Actual validatin message :Record Saved Successfully. :is not equal expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test failed : Record Saved Successfull. :Actual validatin message :Record Saved Successfully. :is not equal expected [true] but found [false]
at Transactions.StatementCollection.FieldValidation(StatementCollection.java:158)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- FieldValidation -->
  <testcase name="verifyCollectedAmt" time="0.089" classname="Transactions.StatementCollection"/>
</testsuite> <!-- Test -->
